name: open_signup_login_page1_signup
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  purchases_flutter: ^6.29.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  google_mobile_ads: ^5.1.0
  image_picker: ^1.1.0
  flutter_card_swiper: ^7.0.0
  fluttertoast: ^8.2.5
  intl: ^0.18.0
  upi_india: ^3.0.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Island Moments
      fonts: 
        - asset: assets/fonts/IslandMomentsRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Tiro Devanagari Hindi
      fonts: 
        - asset: assets/fonts/TiroDevaHindiRegular.ttf
          weight: 400


    - family: Jost
      fonts: 
        - asset: assets/fonts/JostSemiBold.ttf
          weight: 600
        - asset: assets/fonts/JostRomanRegular.ttf
          weight: 400
    - family: Inria Sans
      fonts: 
        - asset: assets/fonts/InriaSansRegular.ttf
          weight: 400
        - asset: assets/fonts/InriaSansBold.ttf
          weight: 700
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishBold.ttf
          weight: 700
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MulishExtraBold.ttf
          weight: 800      
    - family: Inika
      fonts: 
        - asset: assets/fonts/Inika.ttf
          weight: 400
        - asset: assets/fonts/InikaBold.ttf
          weight: 700  
 
