final url="https://f33b-2401-4900-1f32-8fff-00-20a-5c73.ngrok-free.app/";
// final url="http://192.168.96.117:8000/";
final registerRoute=url+"register";
final loginRoute=url+"login";
final checkUserRoute=url+"checkUser";
final checkInstaRoute=url+"checkInsta";
final checkSnapRoute=url+"checkSnap";
final claimGemsRoute =url+"addViaClaimButton";
final getprofileRoute= url+"getProfile";